### ISSUE TITLE
Установка

### ISSUE THREAD

**Issue by wisesokol** [AlexxIT/MediaExtractorPro#1]
День добрый. А как установить. Прошу прощения за глупый вопрос.
В папку custom comp кинул. В Automation.yaml добавил. Не видит сервис при запуске.
Error while executing automation automation.auto_play_music_on_nest_mini. Service not found for call_service at pos 1: Unable to find service media_extractor/play_media

**Comment by AlexxIT** [comment]
Добрый. `media_extractor.play_media`, откуда там косая.

**Comment by wisesokol** [comment]
В конфиге точка стоит
- alias: Auto play music on Nest mini
  trigger:
    platform: state
    entity_id: light.Nest
    to: "on"
  action:
    service: media_extractor.play_media
    entity_id: media_player.gostinaia
    data:
      media_content_id: https://www.youtube.com/watch?v=rSYwtllbweY&list=RDrSYwtllbweY&start_radio=1
      media_content_type: music

**Comment by wisesokol** [comment]
Сорян. Забыл объявить его в Configuration.yaml.
media_extractor:
Работает.
Перемотка на след трек возможна?

**Comment by AlexxIT** [comment]
Перемотка должна работать.

**Comment by wisesokol** [comment]
Обновил до105,5 и все заработало. Спасибо. Были проблемы с Youtube dll, исправили.
