### ISSUE TITLE
Ошибка при запуске плэйлиста

### ISSUE THREAD

**Issue by wisesokol** [AlexxIT/MediaExtractorPro#2]
Добрый день.
С неделю назад появилась ошибка при запуске плейлиста.

`Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for media_extractor doing I/O at custom_components/media_extractor/__init__.py, line 76: media = ydl.extract_info(url, download=False, process=False)`

Home Assistant 0.112.4
Возможно она возникла после перехода на 112.4, не обратил внимания.

**Comment by AlexxIT** [comment]
Поправлено в последней версии
