### ISSUE TITLE
Can't get hass URL

### ISSUE THREAD

**Issue by randomboygh** [AlexxIT/MediaExtractorPro#5]
Сделал все по инструкции, получил две ошибки.

Первая:
> Logger: custom_components.media_extractor
> Source: custom_components/media_extractor/__init__.py:51
> Integration: media_extractor (documentation, issues)
> First occurred: 18:48:12 (1 occurrences)
> Last logged: 18:48:12
> Can't get hass URL

Вторая:
> Logger: homeassistant.setup
> Source: setup.py:178
> First occurred: 18:48:12 (1 occurrences)
> Last logged: 18:48:12
> Setup failed for media_extractor: Integration failed to initialize.

Соответственно, сервисов типа media_extractor.play_media не появилось

**Comment by AlexxIT** [comment]
Должны быть настроены внешний и локальный адреса Hass.

**Comment by randomboygh** [comment]
Помогло, спасибо.
Теперь, правда, появилась другая проблема:
`ERROR: YandexMusic has considered youtube-dl requests automated and asks you to solve a CAPTCHA. You can either wait for some time until unblocked and optionally use --sleep-interval in future or alternatively you can go to https://music.yandex.ru/ solve CAPTCHA, then export cookies and pass cookie file to youtube-dl with --cookies`
К вашему компоненту это не относится, как я понимаю, но было бы интересно узнать, как это решить
